#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
      register: terraform

    - name: add terraform host server to inventory
      add_host:
        name: "{{ terraform.outputs.server.value }}"
        groups:
           - server

    - name: add terraform host agent to inventory
      add_host:
        name: "{{ terraform.outputs.agent.value }}"
        groups:
           - agents

- name: setup shared resources
  hosts: all
  become: yes
  gather_facts: no
  remote_user: root

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.zabbix_repository
    - role: robertdebock.zabbix_agent

<<<<<<< HEAD
- name: setup server resources
  hosts: server
  become: yes
  gather_facts: yes
  remote_user: root

  roles:
    - role: robertdebock.buildtools
    - role: robertdebock.container_docs
    - role: robertdebock.core_dependencies
    - role: robertdebock.mysql
    - role: robertdebock.epel
    - role: robertdebock.selinux
    - role: robertdebock.python_pip
    - role: robertdebock.openssl
    - role: robertdebock.httpd
    - role: robertdebock.php
    - role: robertdebock.zabbix_agent
    - role: robertdebock.zabbix_server
    - role: robertdebock.zabbix_web
=======
    - name: flush handlers
      meta: flush_handlers

    - name: create rancher server container
      docker_container:
        name: rancher
        image: rancher/rancher
        restart_policy: always
        privileged: yes
        ports:
          - "80:80"
          - "443:443"

    - name: show rancher endpoint
      debug:
        msg: "Rancher is installed at https://{{ ansible_fqdn }}/"

  handlers:
    - name: reboot
      reboot:
>>>>>>> f6dbc31f2fe5704d06e226c7fa0ec235506627d7
